#### Key points to remember
* np.linalg.solve() uses LU decomposition (LU factorization)
* how does it work more or less (with time it will be difficult to remember all)

## LU decomposition (motivation)
***x=np.linalg.solve(A, b)*** # uses LU decomposition not Gaussian Elimination!!!
(thats what you used during your homework)

***A_inv=np.linalg.inv(A)*** # uses LU decomposition !!!
(thats what you used during your homework)

https://software.intel.com/sites/products/documentation/doclib/mkl_sa/11/mkl_lapack_examples/cgesv.htm

## Advantages of LU decomposition vs Gaussian Elimination
* classical problem Ax=b
* Gaussian elimination is relatively fast but quite often impractical
* there are situations (differential equations) when A is constant and b keeps changing
* so using the Gaussian elimination even when A is constant and only b is changing one has to do all the operations on both arrays! (because we solve the augmented form)
* in other words: for a constant A and many different bs then you only need to calculate the LU decomposition of A once and it can be reused for each b. However with Gauss-Jordan elimination you would have to re-do all the work for each b
* why: because if b is changing we have to redo all the operations so there must be a better method
* besides GE is unstable sometimes
* if Ax = b, then for a constant A and many different bs then you only need to calculate the LU decomposition of A once and it can be reused for each b. However with Gauss-Jordan elimination you would have to re-do all the work for each b

The system of equations 

$$ A \textbf{x} =  \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn} 
\end{bmatrix} 
\begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots\\
x_{n} 
\end{bmatrix}  = b = 
\begin{bmatrix}
b_{1} \\
b_{2} \\
\vdots\\
b_{n} 
\end{bmatrix}$$

### What is LU decomposition and how it works
LU stands for Lower Upper, here is why:

A matrix A can be decomposed into a product of an lower triangle and upper triangle matrices

                                          [lower triangle][upper triangle]

$$A=LU$$
$$ A = 
\begin{bmatrix}
a_{11} & a_{12} &  a_{13} \\
a_{21} & a_{22} &  a_{23} \\
a_{31} & a_{32} &  a_{33}
\end{bmatrix}
 =
\begin{bmatrix}
1 & 0 &  0 \\
L_{21} & 1 &  0 \\
L_{31} & L_{32} &  1
\end{bmatrix}
\begin{bmatrix}
U_{11} & U_{12} &  U_{13} \\
0 & U_{22} &  U_{23} \\
0 & 0 &  U_{33}
\end{bmatrix}
$$

* The decomposition (factorization) is basically done the same way as Gaussian elimination 
* but how from one matrix two matrices appear?
* we can multiply any matrix my identity ***I*** matrix and this doesnt change anything 
* its like $ 1*x = x$
$$
\begin{bmatrix}
1 & 0 &  0 \\
0 & 1 &  0 \\
0 & 0 &  1
\end{bmatrix}
\begin{bmatrix}
a_{11} & a_{12} &  a_{13} \\
a_{21} & a_{22} &  a_{23} \\
a_{31} & a_{32} &  a_{33}
\end{bmatrix}
$$
and on those two matrices we do the operations as explained in the previous class
until one gets two lower and upper matrices

In [1]:
# proof
import numpy as np
I=np.identity(3)
print('I=\n',I)

A=np.array([[6, 18,3],
           [2,12,1],
           [4, 15,3]])
print('\nA=\n',A)
print('\nI matmul A\n',np.matmul(I,A))

I=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A=
 [[ 6 18  3]
 [ 2 12  1]
 [ 4 15  3]]

I matmul A
 [[ 6. 18.  3.]
 [ 2. 12.  1.]
 [ 4. 15.  3.]]


### How do we use it to solve system of linear equations
* with this we prove that we dont change A and we can substitute it with a dot product of two matrices LoweUpper
* but how do we use it to solve a system of linear equations
* well we can use backward and forward substitution

$$ A \textbf{x} =  \begin{bmatrix}
L_{11} & 0 & \cdots & 0 \\
L_{21} & L_{22} & \cdots & 0 \\
\vdots & \vdots & & \vdots\\
L_{m1} & L_{m2} & \cdots & L_{mn} 
\end{bmatrix} 
\begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots\\
x_{n} 
\end{bmatrix}   = 
\begin{bmatrix}
b_{1} \\
b_{2} \\
\vdots\\
b_{n} 
\end{bmatrix}
$$

$$
\begin{align*} 
L_{11}x_1&  &= b_1 \\
L_{21}x_1& + L_{22}x_2 &= b_2 \\
L_{n1}x_1& + L_{n2}x_2 + \dots + L_{mn}x_n &= b_2 
\end{align*} 
$$

$$
x_1=\frac{b_1}{L_{11}}
$$

$$
x_2=\frac{b_2 - L_{21}x_1}{L_{22}}
$$

$$
x_n=\frac{b_n - \sum_{j=1}^{n-1}L_{nj}x_j}{L_{nn}}
$$


This was a forward substitution but because we have two matrices we actually do it twice
forwar and backward substitution but the principle is the same

## How does it work in practice

$$6 x +  18 y + 3 z = 3$$
$$2 x +  12 y + 1 z = 19$$
$$4 x +  15 y + 3 z = 0$$

$$ A \textbf{x} = b \equiv   
\begin{bmatrix}
6 & 18 &  3 \\
2 & 12 &  0 \\
4 & 15 &  3
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z 
\end{bmatrix}   = 
\begin{bmatrix}
b_{1} \\
b_{2} \\
b_{3} 
\end{bmatrix}
$$

first we can decompose A

$$ 
\begin{bmatrix}
6 & 18 &  3 \\
2 & 12 &  0 \\
4 & 15 &  3
\end{bmatrix}
 =
\begin{bmatrix}
3 & 0 &  0 \\
1 & 6 &  0 \\
2 & 3 &  1
\end{bmatrix}
\begin{bmatrix}
2 & 6 &  1 \\
0 & 1 &  0 \\
0 & 0 &  1
\end{bmatrix}
$$

$$A=LU$$

$$Ax=b$$
$$LUx=b$$

we can substitute $Ux$ with some vector $y$ for example so we get
$$y=
\begin{bmatrix}
u \\
v \\
w 
\end{bmatrix}   
$$

$$Ly=b$$

$$
\begin{bmatrix}
3 & 0 &  0 \\
1 & 6 &  0 \\
2 & 3 &  1
\end{bmatrix}
\begin{bmatrix}
u \\
v \\
w 
\end{bmatrix}   = 
\begin{bmatrix}
b_{1} \\
b_{2} \\
b_{3} 
\end{bmatrix}
$$

and we do the forward substitution
$$y=
\begin{bmatrix} 
1 \\
3 \\
-11 
\end{bmatrix}
$$

next step we do use the upper matrix to solve:

$$
\begin{bmatrix}
2 & 6 &  1 \\
0 & 1 &  0 \\
0 & 0 &  1
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z 
\end{bmatrix}   = 
\begin{bmatrix}
1 \\
3 \\
-11 
\end{bmatrix}
$$

and we use backward substitution to finally get 

$$x=
\begin{bmatrix} 
-3 \\
3 \\
-11 
\end{bmatrix}
$$


In [2]:
# lets double check
b=np.array([[3.],[19],[0]])

A=np.array([[6., 18,3],
           [2,12,1],
           [4, 15,3]])
print('\nA=\n',A)
L=np.array([[3., 0,0],
           [1,6,0],
           [2, 3,1]])
print('\nL=\n',L)
U=np.array([[2., 6,1],
           [0,1,0],
           [0, 0,1]])
print('\nU=\n',U)
print('\nL matmul U\n',np.matmul(L,U))


A=
 [[ 6. 18.  3.]
 [ 2. 12.  1.]
 [ 4. 15.  3.]]

L=
 [[3. 0. 0.]
 [1. 6. 0.]
 [2. 3. 1.]]

U=
 [[2. 6. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]

L matmul U
 [[ 6. 18.  3.]
 [ 2. 12.  1.]
 [ 4. 15.  3.]]


In [3]:
import numpy as np
def forward_sub(L, b):
    """x = forward_sub(L, b) is the solution to L x = b
       L must be a lower-triangular matrix
       b must be a vector of the same leading dimension as L
    """
    n = L.shape[0]
    x = np.zeros(n)
    for i in range(n):
        tmp = b[i].copy()
        for j in range(i):
            tmp -= L[i,j] * x[j]
        x[i] = tmp / L[i,i]
    return x

In [4]:
import numpy as np
def back_sub(U, b):
    """x = back_sub(U, b) is the solution to U x = b
       U must be an upper-triangular matrix
       b must be a vector of the same leading dimension as U
    """
    n = U.shape[0]
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        tmp = b[i].copy()
        for j in range(i+1, n):
            tmp -= U[i,j] * x[j]
        x[i] = tmp / U[i,i]
    return x

In [5]:
y=forward_sub(L, b)
print(y)

[  1.   3. -11.]


In [6]:
x=back_sub(U, y)
print(x)

[ -3.   3. -11.]


In [7]:
b=np.array([[3.],[19],[0]])

A=np.array([[6., 18,3],
           [2,12,1],
           [4, 15,3]])

x=np.linalg.solve(A,b)
print(x)

[[ -3.]
 [  3.]
 [-11.]]


## Pivot strategies:

The previous method of Gaussian Elimination for finding solutions of linear systems is mathematically exact, however round-off errors that appear in computational arithmetics can represent a real problem when high accuracy is required.

In order to illustrate this, consider the next situation:

$$ E_1: 0.00300x_1 + 59.14x_2 = 59.17 $$
$$ E_2: 5.291x_1 - 6.130x_2 = 46.78 $$

Using four-digit arithmetic we obtain:

**1.** Constructing the augmented matrix:

$$ \left[ \matrix{
0.003 & 59.14 & \vdots & 59.17 \\
5.291 & -6.130 & \vdots & 46.78
}\right] $$

**2.** Applying the reduction with the first pivot, we obtain:

$$(E_1 + m E_2)\rightarrow (E_1)$$

where:

$$m = -\frac{a_{21}}{a_{11}} = -\frac{5.291}{0.003} = 1763.666\cdots \approx 1764$$

In this step, we have taken the first four digits. This leads us to:

$$ \left[ \matrix{
0.003 & 59.14 & \vdots & 59.17 \\
0 & -104300 & \vdots & -104400
}\right] $$

The exact system is instead

$$ \left[ \matrix{
0.003 & 59.14 & \vdots & 59.17 \\
0 & -104309.37\bar{6} & \vdots & -104309.37\bar{6}
}\right] $$

Using the solution $x_2 \approx 1.001$, we obtain

$$ x_1 \approx \frac{59.17 - (59.14)(1.001)}{0.00300} = -10 $$

The exact solution is however:

$$ x_1 = 10.00 $$

The source of such a large error is that the factor $59.14/0.00300 \approx 20000$. This quantity is propagated through the combination steps of the Gaussian Elimination, yielding a complete wrong result.

### LU with pivoting
Earlier we saw that without the pivoting 

$$A=LU$$

but the actual optimized algorithm there is one more extra matrix called Permutation Matrix

$$A=PLU$$


### P, L, U = scipy.linalg.lu(A)

In [8]:
# proof that 𝑃𝐴=𝐿𝑈
import scipy.linalg
A= np.array ([[10E-8 ,2] ,[3 ,4]])
P, L, U = scipy.linalg.lu(A)
print('\nA=\n',A)
print('\nP matmul A\n',np.matmul(P,A))
print('\nL matmul U\n',np.matmul(L,U))


A=
 [[1.e-07 2.e+00]
 [3.e+00 4.e+00]]

P matmul A
 [[3.e+00 4.e+00]
 [1.e-07 2.e+00]]

L matmul U
 [[3.e+00 4.e+00]
 [1.e-07 2.e+00]]


A=PLU

In [5]:
import scipy.linalg
import numpy as np
A=np.array([[1., 1,1],
           [2,3,5],
           [4, 6,8]])
print(A)
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)
print(P@L@U)

[[1. 1. 1.]
 [2. 3. 5.]
 [4. 6. 8.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.    1.  ]]
[[ 4.   6.   8. ]
 [ 0.  -0.5 -1. ]
 [ 0.   0.   1. ]]
[[1. 1. 1.]
 [2. 3. 5.]
 [4. 6. 8.]]


# x=np.linalg.solve(A,b)

## everything above was to show how the and the above is to remember how to use
## we only showed that `np.linalg.solve` uses LU decomposition

x=np.linalg.solve(A,b)

works

*(Check with the numpy original routine)

In [10]:
# so lets double check with the previous example
b=np.array([[3.],[19],[0]])

A=np.array([[6., 18,3],
           [2,12,1],
           [4, 15,3]])

print('\nA=\n',A)
print('\nb=\n',b)
x=np.linalg.solve(A,b)
print('\n x= \n',x)



A=
 [[ 6. 18.  3.]
 [ 2. 12.  1.]
 [ 4. 15.  3.]]

b=
 [[ 3.]
 [19.]
 [ 0.]]

 x= 
 [[ -3.]
 [  3.]
 [-11.]]


## Matrix Inversion... Almost a new way of solving the system of linear equations)

Asumming a nonsingular matrix $A$, if a matrix $A^{-1}$ exists, with $AA^{-1} = I$ and $A^{-1}A = I$, where $I$ is the identity matrix, then $A^{-1}$ is called the inverse matrix of $A$. If such a matrix does not exist, $A$ **is said to be a singular matrix.**

A corollary of this definition is that $A$ is also the inverse matrix of $A^{-1}$.

Once defined the Gaussian Elimination method, it is possible to extend it in order to find the inverse of any nonsingular matrix.
Let's consider the next equation:

$$ AA^{-1} = AB= \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & & \vdots \\
a_{m1} & a_{n2} & \cdots & a_{nn} \\
\end{bmatrix}
\begin{bmatrix}
b_{11} & b_{12} & \cdots & b_{1n} \\
b_{21} & b_{22} & \cdots & b_{2n} \\
\vdots & \vdots & & \vdots\\
b_{n1} & b_{n2} & \cdots & b_{nn} \\
\end{bmatrix} = 
\begin{bmatrix}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & 1 \\
\end{bmatrix}$$

This can be rewritten as a set of $n$ systems of equations, i.e.

$$\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn} \\
\end{bmatrix}
\begin{bmatrix}
b_{11} \\
b_{21} \\
\vdots \\
b_{n1} \\
\end{bmatrix} = 
\begin{bmatrix}
1 \\
0 \\
\vdots \\
0 \\
\end{bmatrix}$$

$$\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn} 
\end{bmatrix}
\begin{bmatrix}
b_{12} \\
b_{22} \\
\vdots \\
b_{n2} \\
\end{bmatrix} = 
\begin{bmatrix}
0 \\
1 \\
\vdots \\
0 \\
\end{bmatrix}$$

$$\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn}  \\
\end{bmatrix}
\begin{bmatrix}
b_{1n} \\
b_{2n} \\
\vdots \\
b_{nn} \\
\end{bmatrix} = 
\begin{bmatrix}
0 \\
0 \\
\vdots \\
1 \\
\end{bmatrix}$$

These systems can be solved individually by using Gaussian Elimination, however we can mix all the problems, obtaining the augmented matrix:

$$\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} & \vdots & 1 & 0 & \cdots & 0 \\
a_{21} & a_{22} & \cdots & a_{2n} & \vdots & 0 & 1 & \cdots & 0 \\
\vdots & \vdots & & \vdots & \vdots & \vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn} & \vdots & 0 & 0 & \cdots & 1
\end{bmatrix}$$

Now, applying Gaussian Elimination we can obtain a upper diagonal form for the first matrix. Completing the steps using forwards elimination we can convert the first matrix into the identity matrix, obtaining 

$$\begin{bmatrix}
1 & 0 & \cdots & 0 & \vdots & b_{11} & b_{12} & \cdots & b_{1n} \\
0 & 1 & \cdots & 0 & \vdots & b_{21} & b_{22} & \cdots & b_{2n} \\
\vdots & \vdots & \ddots & \vdots & \vdots & \vdots & \vdots & & \vdots\\
0 & 0 & \cdots & 1 & \vdots & b_{n1} & b_{n2} & \cdots & b_{nn}
\end{bmatrix}$$

Where the second matrix is then the inverse $B=A^{-1}$.

* this can be easily achieved by using Gauss-Jordan elimination on augmented matrix

### Try using `upper diagonal` and `elimination` function from the previous class return inverted matrix from given matrix `A`. 

### Identity matrix in Python
recall the indentity matrix... ones on the diagonal and zero elsewhere

For any matrix:

$$
\begin{bmatrix}
1 & 0 &  0 \\
0 & 1 &  0 \\
0 & 0 &  1
\end{bmatrix}
\begin{bmatrix}
a_{11} & a_{12} &  a_{13} \\
a_{21} & a_{22} &  a_{23} \\
a_{31} & a_{32} &  a_{33}
\end{bmatrix}
=
\begin{bmatrix}
a_{11} & a_{12} &  a_{13} \\
a_{21} & a_{22} &  a_{23} \\
a_{31} & a_{32} &  a_{33}
\end{bmatrix}
\begin{bmatrix}
1 & 0 &  0 \\
0 & 1 &  0 \\
0 & 0 &  1
\end{bmatrix}
=
\begin{bmatrix}
a_{11} & a_{12} &  a_{13} \\
a_{21} & a_{22} &  a_{23} \\
a_{31} & a_{32} &  a_{33}
\end{bmatrix}
$$

so
$$IA=AI=A$$

In [2]:
# proof
import numpy as np
I=np.identity(3)
print('I=\n',I)

A=np.array([[6, 18,3],
           [2,12,1],
           [4, 15,3]])
print('\nA=\n',A)
print('\nI x A\n',I@A)

I=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A=
 [[ 6 18  3]
 [ 2 12  1]
 [ 4 15  3]]

I x A
 [[ 6. 18.  3.]
 [ 2. 12.  1.]
 [ 4. 15.  3.]]


# but all you have to remember is: ` A_inv=np.linalg.inv(A)`

* looks useless but the above implies that if:
$$𝐼𝐴=𝐴𝐼=𝐴$$

* then 
$$𝐴=𝐴𝐼$$

* so 
that means there exists a matrix that inverts the previous one in such a way:

$$AA^{-1}=I$$

* $A^{-1}$ is like putting the matrix on the other side of the equation

In [13]:
import numpy as np

A=np.array([[6, 18,3],
           [2,12,1],
           [4, 15,3]])

A_inv=np.linalg.inv(A)
print('\nA=\n',A)

print('\nA^-1 =\n',A_inv)

# lets check that AA^-1=I

print('\nA A^-1 =\n',np.matmul(A,A_inv))



A=
 [[ 6 18  3]
 [ 2 12  1]
 [ 4 15  3]]

A^-1 =
 [[ 0.58333333 -0.25       -0.5       ]
 [-0.05555556  0.16666667  0.        ]
 [-0.5        -0.5         1.        ]]

A A^-1 =
 [[ 1.00000000e+00  2.22044605e-16  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  0.00000000e+00  1.00000000e+00]]


# How can this be useful in solving system of linear equations:
Inverted matrix serves as "matrix division"

* if $Ax=b$


$$6 x +  18 y + 3 z = 3$$
$$2 x +  12 y + 1 z = 19$$
$$4 x +  15 y + 3 z = 0$$

$$ A \textbf{x} = b \equiv   
\begin{bmatrix}
6 & 18 &  3 \\
2 & 12 &  0 \\
4 & 15 &  3
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z 
\end{bmatrix}   = 
\begin{bmatrix}
b_{1} \\
b_{2} \\
b_{3} 
\end{bmatrix}
$$


then ***$x=A^{-1}b$*** !!! And we just solve it for x

### lets check this out

In [3]:
# lets double check
b=np.array([[3.],[19],[0]])

A=np.array([[6., 18,3],
           [2,12,1],
           [4, 15,3]])

In [10]:
print('A=\n',A)
print()
A_inv=np.linalg.inv(A)
print('Ainv=\n',A_inv)

A=
 [[ 6. 18.  3.]
 [ 2. 12.  1.]
 [ 4. 15.  3.]]

Ainv=
 [[ 0.58333333 -0.25       -0.5       ]
 [-0.05555556  0.16666667  0.        ]
 [-0.5        -0.5         1.        ]]


applying: $x=A^{-1}b$

In [13]:
print('Ainv x b=\n',A_inv@b)

Ainv x b=
 [[ -3.]
 [  3.]
 [-11.]]


Numerically using numpy linear algebra package:  
`x=np.linalg.solve(A,b)`

## and now compare it with:  `x=np.linalg.solve(A,b)`

In [14]:
# lets double check
b=np.array([[3.],[19],[0]])

A=np.array([[6., 18,3],
           [2,12,1],
           [4, 15,3]])

print('\nb=\n',b)

print('\nA=\n',A)

x=np.linalg.solve(A,b)

print('\nx =\n',x)


b=
 [[ 3.]
 [19.]
 [ 0.]]

A=
 [[ 6. 18.  3.]
 [ 2. 12.  1.]
 [ 4. 15.  3.]]

x =
 [[ -3.]
 [  3.]
 [-11.]]


* numpy.inv also uses LU decomposion

## Matrix transpose

$$
\begin{bmatrix}
2 & 4 &  -1 \\
-10 & 5 &  1 \\
18 & -7 &  6
\end{bmatrix}^T =
\begin{bmatrix}
2 & -10 &  -18 \\
4 & 5 &  -7 \\
-1 & 11 &  6
\end{bmatrix} 
$$

<img src="imgs/matrix_transpose.png" width="600" />

In [17]:
import numpy as np

A=np.array([[2, 4,-1],
           [-10,5,11],
           [18, -7,6]])
print('A=\n',A)
print('A^T=\n',A.T)

A=
 [[  2   4  -1]
 [-10   5  11]
 [ 18  -7   6]]
A^T=
 [[  2 -10  18]
 [  4   5  -7]
 [ -1  11   6]]


## Matrix Hermitian transpose (complex conjugate transpose of a matrix)

$$
\begin{bmatrix}
1-3i & 6 &  -7i \\
2+i & 8-2i &  1-9i \\
4i & 3+5i &  -2-i
\end{bmatrix} ^H=
\begin{bmatrix}
1+3i & 2-1i &  -4i \\
6 & 8+2i &  3-5i \\
7i & 1+9i &  -2+i
\end{bmatrix} = 
$$

In [18]:
import numpy as np
A=np.matrix([[1+3j, 2-1j,-4j],
           [6,8+2j,3-5j],
           [7j, 1+9j,-2+1j]])
print('A=\n',A)
print('A^H=\n',A.getH())

A=
 [[ 1.+3.j  2.-1.j -0.-4.j]
 [ 6.+0.j  8.+2.j  3.-5.j]
 [ 0.+7.j  1.+9.j -2.+1.j]]
A^H=
 [[ 1.-3.j  6.-0.j  0.-7.j]
 [ 2.+1.j  8.-2.j  1.-9.j]
 [-0.+4.j  3.+5.j -2.-1.j]]
